INSERT INTO Orgao_superior(cod_orgao_superior,nome_orgao_superior) VALUES (22000,'Ministério da Agricultura, Pecuária e Abastec');
INSERT INTO Orgao_superior(cod_orgao_superior,nome_orgao_superior) VALUES (26000,'Ministério da Educação');
INSERT INTO Orgao_superior(cod_orgao_superior,nome_orgao_superior) VALUES (52000,'Ministério da Defesa');
INSERT INTO Orgao_superior(cod_orgao_superior,nome_orgao_superior) VALUES (25000,'Ministério da Economia');
INSERT INTO Orgao_superior(cod_orgao_superior,nome_orgao_superior) VALUES (44000,'Ministério do Meio Ambiente');
INSERT INTO Orgao_superior(cod_orgao_superior,nome_orgao_superior) VALUES (30000,'Ministério da Justiça e Segurança Pública');
INSERT INTO Orgao_superior(cod_orgao_superior,nome_orgao_superior) VALUES (24000,'Ministério da Ciência, Tecnologia, Inovações');
INSERT INTO Orgao_superior(cod_orgao_superior,nome_orgao_superior) VALUES (40000,'Ministério do Trabalho');
INSERT INTO Orgao_superior(cod_orgao_superior,nome_orgao_superior) VALUES (32000,'Ministério de Minas e Energia');
INSERT INTO Orgao_superior(cod_orgao_superior,nome_orgao_superior) VALUES (53000,'Ministério do Desenvolvimento Regional');
INSERT INTO Orgao_superior(cod_orgao_superior,nome_orgao_superior) VALUES (38833,'CONSELHO REGIONAL DE QUÍMICA DA 12 REGIÃO');
INSERT INTO Orgao_superior(cod_orgao_superior,nome_orgao_superior) VALUES (36000,'MINISTERIO DA SAUDE');
INSERT INTO Orgao_superior(cod_orgao_superior,nome_orgao_superior) VALUES (38000,'MINISTERIO DO TRABALHO E EMPREGO');
INSERT INTO Orgao_superior(cod_orgao_superior,nome_orgao_superior) VALUES (12000,'Justiça Federal');
INSERT INTO Orgao_superior(cod_orgao_superior,nome_orgao_superior) VALUES (20000,'Presidência da República');
INSERT INTO Orgao_superior(cod_orgao_superior,nome_orgao_superior) VALUES (63000,'Advocacia-Geral da União');
INSERT INTO Orgao_superior(cod_orgao_superior,nome_orgao_superior) VALUES (39000,'Ministério da Infraestrutura');
INSERT INTO Orgao_superior(cod_orgao_superior,nome_orgao_superior) VALUES (54000,'Ministério do Turismo');
INSERT INTO Orgao_superior(cod_orgao_superior,nome_orgao_superior) VALUES (35000,'Ministério das Relações Exteriores');
INSERT INTO Orgao_superior(cod_orgao_superior,nome_orgao_superior) VALUES (55000,'Ministério da Cidadania');
INSERT INTO Orgao_superior(cod_orgao_superior,nome_orgao_superior) VALUES (81000,'Ministério da Mulher, Família e Direitos Huma');
INSERT INTO Orgao_superior(cod_orgao_superior,nome_orgao_superior) VALUES (41000,'MINISTERIO DAS COMUNICACOES');
INSERT INTO Orgao_superior(cod_orgao_superior,nome_orgao_superior) VALUES (37000,'Controladoria-Geral da União');
INSERT INTO Orgao_superior(cod_orgao_superior,nome_orgao_superior) VALUES (28000,'Ministério da Indústria, Comércio Exterior e');
INSERT INTO Orgao_superior(cod_orgao_superior,nome_orgao_superior) VALUES (3000,'Tribunal de Contas da União');
INSERT INTO Orgao_superior(cod_orgao_superior,nome_orgao_superior) VALUES (25201,'Banco Central do Brasil - Orçamento Fiscal e');

